# Generated by Django 4.2 on 2023-04-29 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_photo_alter_new_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cesid',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Cesid'),
            preserve_default=False,
        ),
    ]
