# Generated by Django 4.1.7 on 2023-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_cesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=256, verbose_name='Mənşə'),
        ),
    ]
