# Generated by Django 4.1.7 on 2023-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Ad')),
                ('unvan', models.CharField(max_length=255, verbose_name='Unvan')),
                ('tel1', models.CharField(max_length=20, verbose_name='Telefon1')),
                ('tel2', models.CharField(max_length=20, verbose_name='Telefon2')),
                ('tel3', models.CharField(max_length=20, verbose_name='Telefon3')),
                ('tel4', models.CharField(max_length=20, verbose_name='Telefon4')),
                ('tel5', models.CharField(max_length=20, verbose_name='Telefon5')),
            ],
        ),
    ]
