# Generated by Django 4.1.7 on 2023-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_map_unvanlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='tel1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon1'),
        ),
        migrations.AlterField(
            model_name='map',
            name='tel2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon2'),
        ),
        migrations.AlterField(
            model_name='map',
            name='tel3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon3'),
        ),
        migrations.AlterField(
            model_name='map',
            name='tel4',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon4'),
        ),
        migrations.AlterField(
            model_name='map',
            name='tel5',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon5'),
        ),
        migrations.AlterField(
            model_name='map',
            name='unvan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Unvan'),
        ),
    ]
