# Generated by Django 4.1.7 on 2023-05-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_map_unvan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255, verbose_name='AzAbrau Alt')),
                ('field2', models.CharField(max_length=255, verbose_name='Şəki Şərabı Alt')),
                ('field3', models.CharField(max_length=255, verbose_name='Haqqımızda Başlıq')),
                ('field4', models.CharField(max_length=255, verbose_name='Haqqımızda description')),
            ],
        ),
    ]
